Jonnitto:
  Headline:
    container: false
    defaultTagName: h1

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.Headline:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.Headline: true
